import { randomUUID } from "node:crypto";
import { getDatabase } from "../database/database";
import { audit, requireSession } from "./auth";
export interface ProductInput{sessionId:string;name:string;barcode?:string;sku?:string;category?:string;brand?:string;costPrice:number;sellingPrice:number;wholesalePrice?:number;stock?:number;minStock?:number;unit?:string}
function ctx(id:string){return requireSession(id)}
export function dashboard(sessionId:string){const {userId}=ctx(sessionId);const db=getDatabase();const u=db.prepare(`SELECT business_id,store_id FROM users WHERE id=?`).get(userId) as any;const sales=db.prepare(`SELECT COALESCE(SUM(total),0) total,COUNT(*) count,COALESCE(SUM((SELECT SUM(quantity) FROM sale_items si WHERE si.sale_id=s.id)),0) items FROM sales s WHERE s.store_id=? AND date(s.created_at)=date('now','localtime') AND s.status='COMPLETED'`).get(u.store_id) as any;const low=db.prepare(`SELECT COUNT(*) count FROM products WHERE business_id=? AND active=1 AND stock<=min_stock`).get(u.business_id) as any;return{salesTotal:Number(sales.total),transactions:Number(sales.count),itemsSold:Number(sales.items),lowStock:Number(low.count)}}
export function listProducts(sessionId:string,query=""){const {userId}=ctx(sessionId);const db=getDatabase();const u=db.prepare(`SELECT business_id FROM users WHERE id=?`).get(userId) as any;const q=`%${query.trim()}%`;return db.prepare(`SELECT p.*,COALESCE(c.name,'Uncategorized') category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.business_id=? AND p.active=1 AND (p.name LIKE ? OR p.barcode LIKE ? OR p.sku LIKE ? OR p.brand LIKE ?) ORDER BY p.name LIMIT 200`).all(u.business_id,q,q,q,q)}
export function createProduct(input:ProductInput){const {userId}=ctx(input.sessionId);const db=getDatabase();const u=db.prepare(`SELECT business_id FROM users WHERE id=?`).get(userId) as any;if(!input.name.trim()||input.sellingPrice<0)throw new Error("Enter a product name and valid selling price.");const id=randomUUID(),now=new Date().toISOString(),sku=input.sku?.trim()||`SKU-${Date.now()}`;try{db.prepare(`INSERT INTO products(id,business_id,sku,barcode,name,brand,cost_price,selling_price,wholesale_price,stock,min_stock,unit,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,u.business_id,sku,input.barcode?.trim()||null,input.name.trim(),input.brand?.trim()||null,input.costPrice,input.sellingPrice,input.wholesalePrice||0,input.stock||0,input.minStock||0,input.unit||"pcs",now,now);audit(userId,"CREATE","PRODUCT",id,`Created ${input.name}`);return db.prepare(`SELECT * FROM products WHERE id=?`).get(id)}catch(e){throw new Error("That SKU may already exist. Choose another internal SKU.")}}
export function startShift(sessionId:string,openingCash:number){const {userId}=ctx(sessionId);const db=getDatabase();const u=db.prepare(`SELECT store_id FROM users WHERE id=?`).get(userId) as any;let r=db.prepare(`SELECT id FROM cash_registers WHERE store_id=? LIMIT 1`).get(u.store_id) as any;if(!r){r={id:randomUUID()};db.prepare(`INSERT INTO cash_registers(id,store_id,name,created_at) VALUES(?,?,?,?)`).run(r.id,u.store_id,"Main Register",new Date().toISOString())}const open=db.prepare(`SELECT id FROM shifts WHERE register_id=? AND status='OPEN'`).get(r.id);if(open)throw new Error("A cash shift is already open.");const id=randomUUID();db.prepare(`INSERT INTO shifts(id,register_id,user_id,opening_cash,opened_at,status) VALUES(?,?,?,?,?,?)`).run(id,r.id,userId,openingCash,new Date().toISOString(),"OPEN");audit(userId,"OPEN_SHIFT","SHIFT",id,`Opening cash ${openingCash}`);return{id,openingCash}}
export function currentShift(sessionId:string){const {userId}=ctx(sessionId);return getDatabase().prepare(`SELECT sh.*,cr.name register_name FROM shifts sh JOIN cash_registers cr ON cr.id=sh.register_id WHERE sh.user_id=? AND sh.status='OPEN' ORDER BY sh.opened_at DESC LIMIT 1`).get(userId)||null}
export interface SaleInput{sessionId:string;items:{productId:string;quantity:number}[];paymentMethod:string;cashReceived:number;discount:number;customerId?:string}
export function completeSale(input:SaleInput){const {userId}=ctx(input.sessionId);const db=getDatabase();const u=db.prepare(`SELECT store_id,business_id FROM users WHERE id=?`).get(userId) as any;if(!input.items.length)throw new Error("Add at least one product to the sale.");const shift=currentShift(input.sessionId) as any;if(!shift)throw new Error("Start your cash shift before taking a sale.");const products=input.items.map(i=>{const p=db.prepare(`SELECT * FROM products WHERE id=? AND business_id=? AND active=1`).get(i.productId,u.business_id) as any;if(!p)throw new Error("One of the products is no longer available.");if(i.quantity<=0||p.stock<i.quantity)throw new Error(`${p.name} does not have enough stock.`);return{...i,p}});const subtotal=products.reduce((n,i)=>n+i.p.selling_price*i.quantity,0),discount=Math.max(0,input.discount||0),tax=0,total=Math.max(0,subtotal-discount),cash=input.paymentMethod==="CASH"?Math.max(0,input.cashReceived):0;if(input.paymentMethod==="CASH"&&cash<total)throw new Error(`Cash received is less than the total. Enter at least ${total.toFixed(2)}.`);const change=cash-total,id=randomUUID(),receipt=`OLYR-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Date.now().toString().slice(-6)}`,now=new Date().toISOString();db.exec("BEGIN IMMEDIATE");try{db.prepare(`INSERT INTO sales(id,store_id,user_id,customer_id,shift_id,receipt_number,subtotal,discount,tax,total,payment_method,cash_received,change_due,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,u.store_id,userId,input.customerId||null,shift.id,receipt,subtotal,discount,tax,total,input.paymentMethod,cash,change,now);for(const i of products){db.prepare(`INSERT INTO sale_items(id,sale_id,product_id,quantity,unit_price,discount,line_total) VALUES(?,?,?,?,?,?,?)`).run(randomUUID(),id,i.p.id,i.quantity,i.p.selling_price,0,i.p.selling_price*i.quantity);db.prepare(`UPDATE products SET stock=stock-?,updated_at=? WHERE id=?`).run(i.quantity,now,i.p.id);db.prepare(`INSERT INTO inventory_movements(id,product_id,user_id,type,quantity,reference_id,reason,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(randomUUID(),i.p.id,userId,"SALE",-i.quantity,id,"Sale",now)}db.exec("COMMIT");audit(userId,"SALE","SALE",id,`Receipt ${receipt}, total ${total}`);return{saleId:id,receiptNumber:receipt,subtotal,discount,tax,total,paymentMethod:input.paymentMethod,cashReceived:cash,changeDue:change}}catch(e){db.exec("ROLLBACK");throw e}}
export function salesHistory(sessionId:string){const {userId}=ctx(sessionId);const u=getDatabase().prepare(`SELECT store_id FROM users WHERE id=?`).get(userId) as any;return getDatabase().prepare(`SELECT s.receipt_number,s.total,s.payment_method,s.status,s.created_at,u.name cashier FROM sales s JOIN users u ON u.id=s.user_id WHERE s.store_id=? ORDER BY s.created_at DESC LIMIT 100`).all(u.store_id)}
