import { randomUUID } from "node:crypto";
import { getDatabase } from "../database/database";
import { audit, requireSession } from "./auth";

const ctx=(id:string)=>{const {userId}=requireSession(id);const db=getDatabase();const u=db.prepare("SELECT business_id,store_id FROM users WHERE id=?").get(userId) as any;if(!u)throw new Error("User account could not be found.");return {userId,businessId:u.business_id,storeId:u.store_id,db}};

export interface ProductInput { sessionId:string; name:string; barcode?:string; sku?:string; category?:string; brand?:string; costPrice?:number; sellingPrice:number; wholesalePrice?:number; stock?:number; minStock?:number; unit?:string }

export function dashboard(sessionId:string){const c=ctx(sessionId);const sales=c.db.prepare("SELECT COALESCE(SUM(total),0) total,COUNT(*) count,COALESCE(SUM((SELECT SUM(quantity) FROM sale_items si WHERE si.sale_id=s.id)),0) items FROM sales s WHERE s.store_id=? AND date(s.created_at)=date('now','localtime') AND s.status='COMPLETED'").get(c.storeId) as any;const low=c.db.prepare("SELECT COUNT(*) count FROM products WHERE business_id=? AND active=1 AND stock<=min_stock").get(c.businessId) as any;return {salesTotal:Number(sales.total),transactions:Number(sales.count),itemsSold:Number(sales.items),lowStock:Number(low.count)}}

export function listProducts(sessionId:string,query=""){const c=ctx(sessionId);const q=`%${query.trim()}%`;return c.db.prepare("SELECT p.*,COALESCE(cat.name,'Uncategorized') category_name FROM products p LEFT JOIN categories cat ON cat.id=p.category_id WHERE p.business_id=? AND p.active=1 AND (p.name LIKE ? OR COALESCE(p.barcode,'') LIKE ? OR p.sku LIKE ? OR COALESCE(p.brand,'') LIKE ?) ORDER BY p.name LIMIT 300").all(c.businessId,q,q,q,q)}

export function createProduct(input:ProductInput){const c=ctx(input.sessionId);const name=input.name.trim();const price=Number(input.sellingPrice);if(!name)throw new Error("Enter a product name.");if(!Number.isFinite(price)||price<0)throw new Error("Enter a valid selling price.");const sku=(input.sku?.trim()||`P-${Date.now()}-${Math.floor(Math.random()*900+100)}`).toUpperCase();const barcode=input.barcode?.trim()||null;const cost=Math.max(0,Number(input.costPrice)||0);const stock=Math.max(0,Number(input.stock)||0);const min=Math.max(0,Number(input.minStock)||0);const now=new Date().toISOString();let categoryId:string|null=null;if(input.category?.trim()){const found=c.db.prepare("SELECT id FROM categories WHERE business_id=? AND lower(name)=lower(?)").get(c.businessId,input.category.trim()) as any;if(found)categoryId=found.id;else{categoryId=randomUUID();c.db.prepare("INSERT INTO categories(id,business_id,name,created_at) VALUES(?,?,?,?)").run(categoryId,c.businessId,input.category.trim(),now)}}try{const id=randomUUID();c.db.prepare("INSERT INTO products(id,business_id,category_id,sku,barcode,name,brand,cost_price,selling_price,wholesale_price,stock,min_stock,unit,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,c.businessId,categoryId,sku,barcode,name,input.brand?.trim()||null,cost,price,Math.max(0,Number(input.wholesalePrice)||0),stock,min,input.unit?.trim()||"pcs",now,now);if(stock>0)c.db.prepare("INSERT INTO inventory_movements(id,product_id,user_id,type,quantity,reason,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),id,c.userId,"OPENING",stock,"Opening stock",now);audit(c.userId,"CREATE","PRODUCT",id,`Created ${name}`);return c.db.prepare("SELECT * FROM products WHERE id=?").get(id)}catch(e){const message=String(e);if(message.includes("UNIQUE"))throw new Error("That SKU or barcode is already in use. Choose another one.");throw e}}

export function startShift(sessionId:string,openingCash:number){const c=ctx(sessionId);if(!Number.isFinite(openingCash)||openingCash<0)throw new Error("Enter a valid opening cash amount.");let r=c.db.prepare("SELECT id FROM cash_registers WHERE store_id=? LIMIT 1").get(c.storeId) as any;if(!r){r={id:randomUUID()};c.db.prepare("INSERT INTO cash_registers(id,store_id,name,created_at) VALUES(?,?,?,?)").run(r.id,c.storeId,"Main Register",new Date().toISOString())}if(c.db.prepare("SELECT id FROM shifts WHERE register_id=? AND status='OPEN'").get(r.id))throw new Error("A cash shift is already open.");const id=randomUUID();c.db.prepare("INSERT INTO shifts(id,register_id,user_id,opening_cash,opened_at,status) VALUES(?,?,?,?,?,?)").run(id,r.id,c.userId,openingCash,new Date().toISOString(),"OPEN");audit(c.userId,"OPEN_SHIFT","SHIFT",id,`Opening cash ${openingCash}`);return{id,openingCash}}
export function currentShift(sessionId:string){const c=ctx(sessionId);return c.db.prepare("SELECT sh.*,cr.name register_name FROM shifts sh JOIN cash_registers cr ON cr.id=sh.register_id WHERE sh.user_id=? AND sh.status='OPEN' ORDER BY sh.opened_at DESC LIMIT 1").get(c.userId)||null}
export function closeShift(sessionId:string,actualCash:number){const c=ctx(sessionId);const sh=currentShift(sessionId) as any;if(!sh)throw new Error("There is no open shift.");if(!Number.isFinite(actualCash)||actualCash<0)throw new Error("Enter the actual cash in the drawer.");const cashSales=c.db.prepare("SELECT COALESCE(SUM(cash_received),0) total FROM sales WHERE shift_id=? AND status='COMPLETED' AND payment_method='CASH'").get(sh.id) as any;const expected=Number(sh.opening_cash)+Number(cashSales.total);const variance=actualCash-expected;const now=new Date().toISOString();c.db.prepare("UPDATE shifts SET closing_cash=?,closed_at=?,status='CLOSED' WHERE id=?").run(actualCash,now,sh.id);audit(c.userId,"CLOSE_SHIFT","SHIFT",sh.id,`Expected ${expected}, actual ${actualCash}, variance ${variance}`);return{expected,actual:actualCash,variance}}

export interface SaleInput {sessionId:string;items:{productId:string;quantity:number}[];paymentMethod:string;cashReceived:number;discount:number;customerId?:string}
export function completeSale(input:SaleInput){const c=ctx(input.sessionId);if(!input.items.length)throw new Error("Add at least one product to the sale.");const shift=currentShift(input.sessionId) as any;if(!shift)throw new Error("Start your cash shift before taking a sale.");const method=(input.paymentMethod||"CASH").toUpperCase();const products=input.items.map(i=>{if(!Number.isFinite(i.quantity)||i.quantity<=0)throw new Error("Sale quantity must be greater than zero.");const p=c.db.prepare("SELECT * FROM products WHERE id=? AND business_id=? AND active=1").get(i.productId,c.businessId) as any;if(!p)throw new Error("One of the products is no longer available.");if(Number(p.stock)<i.quantity)throw new Error(`${p.name} does not have enough stock.`);return{...i,p}});const subtotal=products.reduce((n,i)=>n+Number(i.p.selling_price)*i.quantity,0);const discount=Math.min(subtotal,Math.max(0,Number(input.discount)||0));const tax=0;const total=Math.max(0,subtotal-discount+tax);const cash=method==="CASH"?Math.max(0,Number(input.cashReceived)||0):0;if(method==="CASH"&&cash<total)throw new Error(`Cash received is less than the total. Enter at least ${total.toFixed(2)}.`);const change=method==="CASH"?cash-total:0;const id=randomUUID();const receipt=`OLYR-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${Date.now().toString().slice(-7)}`;const now=new Date().toISOString();c.db.exec("BEGIN IMMEDIATE");try{c.db.prepare("INSERT INTO sales(id,store_id,user_id,customer_id,shift_id,receipt_number,subtotal,discount,tax,total,payment_method,cash_received,change_due,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,c.storeId,c.userId,input.customerId||null,shift.id,receipt,subtotal,discount,tax,total,method,cash,change,now);for(const i of products){c.db.prepare("INSERT INTO sale_items(id,sale_id,product_id,quantity,unit_price,discount,line_total) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),id,i.p.id,i.quantity,i.p.selling_price,0,i.p.selling_price*i.quantity);c.db.prepare("UPDATE products SET stock=stock-?,updated_at=? WHERE id=?").run(i.quantity,now,i.p.id);c.db.prepare("INSERT INTO inventory_movements(id,product_id,user_id,type,quantity,reference_id,reason,created_at) VALUES(?,?,?,?,?,?,?,?)").run(randomUUID(),i.p.id,c.userId,"SALE",-i.quantity,id,"Sale",now)}c.db.exec("COMMIT");audit(c.userId,"SALE","SALE",id,`Receipt ${receipt}, total ${total}`);return{saleId:id,receiptNumber:receipt,subtotal,discount,tax,total,paymentMethod:method,cashReceived:cash,changeDue:change}}catch(e){c.db.exec("ROLLBACK");throw e}}

export function salesHistory(sessionId:string){const c=ctx(sessionId);return c.db.prepare("SELECT s.id,s.receipt_number,s.total,s.subtotal,s.discount,s.payment_method,s.status,s.created_at,u.name cashier FROM sales s JOIN users u ON u.id=s.user_id WHERE s.store_id=? ORDER BY s.created_at DESC LIMIT 200").all(c.storeId)}
export function inventory(sessionId:string){const c=ctx(sessionId);return c.db.prepare("SELECT p.id,p.name,p.sku,p.barcode,p.stock,p.min_stock,p.unit,p.cost_price,p.selling_price,CASE WHEN p.stock<=p.min_stock THEN 1 ELSE 0 END low_stock FROM products p WHERE p.business_id=? AND p.active=1 ORDER BY p.name").all(c.businessId)}
export function profitReport(sessionId:string){const c=ctx(sessionId);return c.db.prepare("SELECT COALESCE(SUM(si.line_total),0) revenue,COALESCE(SUM(si.quantity*p.cost_price),0) cost,COALESCE(SUM(si.line_total-si.quantity*p.cost_price),0) gross_profit FROM sale_items si JOIN sales s ON s.id=si.sale_id JOIN products p ON p.id=si.product_id WHERE s.store_id=? AND s.status='COMPLETED'").get(c.storeId)}
export function createCustomer(sessionId:string,input:{name:string;phone?:string;email?:string;address?:string}){const c=ctx(sessionId);if(!input.name.trim())throw new Error("Enter a customer name.");const id=randomUUID(),now=new Date().toISOString();c.db.prepare("INSERT INTO customers(id,business_id,name,phone,email,address,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(id,c.businessId,input.name.trim(),input.phone?.trim()||null,input.email?.trim()||null,input.address?.trim()||null,now,now);audit(c.userId,"CREATE","CUSTOMER",id,`Created ${input.name.trim()}`);return c.db.prepare("SELECT * FROM customers WHERE id=?").get(id)}
export function customers(sessionId:string){const c=ctx(sessionId);return c.db.prepare("SELECT * FROM customers WHERE business_id=? ORDER BY name").all(c.businessId)}
